apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/arguments
        value:
          x-message-ttl: 60000
    target:
      kind: Queue
