apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-topology
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: git@github.com:erikarnolds-anzr/rabbitmq-topology
    targetRevision: HEAD
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true