apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: notifications-exchange
  namespace: default
spec:
  name: notifications
  type: direct
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq
